### ISSUE TITLE
Enums not seeing facilityguard

### ISSUE THREAD

**Issue by 1ngush** [Ruemena/RueI#2]
“Delegates” does not work on the method after the spawn of a guard and works after the spawn of all other characteristic roles.

public static AutoElement AutoElement { get; } = AutoElement.Create(Roles.HumanRoles, MyElement).UpdateEvery(TimeSpan.FromSeconds(0.7));

public static AutoElement AutoElement2 { get; } = AutoElement.Create(Roles.MilitaryRoles, MyElement).UpdateEvery(TimeSpan.FromSeconds(1.4));

**Comment by 1ngush** [comment]
![image](https://github.com/Ruemena/RueI/assets/88559709/1235cd4d-549e-4da7-b6b4-2b41e1aecaa6)
![image](https://github.com/Ruemena/RueI/assets/88559709/ee5fc995-2300-4f4f-92d2-18c5251cd72b)

**Comment by Ruemena** [comment]
thanks for pointing this out, rn its accidentally
```csharp
    /// <summary>
    /// Gets the Facility Guard role id.
    /// </summary>
    FacilityGuard = 1 << RoleTypeId.Tutorial,
 ```

**Comment by Ruemena** [comment]
fixed, quick fix :3

**Comment by Ruemena** [comment]
will publish new release soon

**Comment by bgdy1** [comment]
Now AutoElement.Create is disappear(?
