### ISSUE TITLE
Offtop

### ISSUE THREAD

**Issue by deadsharkk** [Ruemena/RueI#3]
Perhaps not directly, but indirectly. The transparency of the text is lost. In one plugin I have a delegate that shows the HUD once every 0.7s, in another plugin I try to show a temporary hint in the OnPickingUpItem event, but after 2-3 times of showing them, all hints lose transparency.
![image](https://github.com/Ruemena/RueI/assets/88559709/b08bdfdd-6d1b-414a-a4a2-6332f247df0a)
![image](https://github.com/Ruemena/RueI/assets/88559709/a4b5a679-fc79-4bde-a919-91515af215ff)
![image](https://github.com/Ruemena/RueI/assets/88559709/5108ede1-8585-420e-844f-36b58a882737)

**Comment by Ruemena** [comment]
ill take a look i think i know whats going on

**Comment by Ruemena** [comment]
lmk if the new release fixes this

**Comment by 1ngush** [comment]
Transparency is lost when you pick up a pickup, which tells you that this is the maximum number of items that you can pick up, i.e. from a system hint. Also, when assigning settempelement in different plugins, they do not overwrite each other, but lie on top with a slight offset, addtempfunctional does not show anything at all
