### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by isurami** [Ruemena/RueI#4]
private static readonly TimedElemRef<SetElement> CraftElement = new();

![image](https://github.com/Ruemena/RueI/assets/88559709/c05af4b7-a8c9-405e-b3b7-addeb0e3d5cd)
![image](https://github.com/Ruemena/RueI/assets/88559709/252053f4-d536-4231-aa35-eef79390ee44)

For example, a loop with an interval of 5 seconds shows hints lasting 10 seconds, in this case 1 hint will show up, and 2 will show up for half a second and reset, because the time of 1 hint is over.

**Comment by kainosekai** [comment]
stupid whore i fuck your mom
